# Generated by Django 5.0.1 on 2024-03-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='completed',
        ),
    ]
