# Generated by Django 5.0.1 on 2024-03-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_instructorapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
    ]
