# Generated by Django 5.0.1 on 2024-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorapplication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
