# Generated by Django 5.0.1 on 2024-01-29 19:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('descirption', models.TextField()),
                ('image', models.ImageField(default='../course_default', upload_to='images/')),
                ('categories', models.CharField(choices=[('Engineering', 'Engineering'), ('', 'Course category'), ('Technology', 'Technology'), ('Art and Creativity', 'Art and Creativity'), ('Health and Fitness', 'Health and Fitness'), ('Science', 'Science'), ('Business', 'Business'), ('New Category', 'New Category'), ('Social Sciences', 'Social Sciences'), ('Marketing', 'Marketing'), ('Languages', 'Languages'), ('Personal Development', 'Personal Development'), ('Design', 'Design')], max_length=50)),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('video_hours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('test_count', models.PositiveIntegerField(default=0)),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
