# Generated by Django 5.0.1 on 2024-01-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Art and Creativity', 'Art and Creativity'), ('Science', 'Science'), ('Personal Development', 'Personal Development'), ('Health and Fitness', 'Health and Fitness'), ('', 'Course category'), ('Technology', 'Technology'), ('Engineering', 'Engineering'), ('Design', 'Design'), ('Business', 'Business'), ('Social Sciences', 'Social Sciences'), ('Languages', 'Languages')], max_length=50),
        ),
    ]
