# Generated by Django 5.0.1 on 2024-01-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='descirption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Social Sciences', 'Social Sciences'), ('Personal Development', 'Personal Development'), ('Business', 'Business'), ('Art and Creativity', 'Art and Creativity'), ('Science', 'Science'), ('Engineering', 'Engineering'), ('', 'Course category'), ('Design', 'Design'), ('Technology', 'Technology'), ('Health and Fitness', 'Health and Fitness'), ('Languages', 'Languages')], max_length=50),
        ),
    ]
