# Generated by Django 5.0.1 on 2024-01-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Design', 'Design'), ('Technology', 'Technology'), ('Art and Creativity', 'Art and Creativity'), ('Languages', 'Languages'), ('Engineering', 'Engineering'), ('Health and Fitness', 'Health and Fitness'), ('Personal Development', 'Personal Development'), ('Science', 'Science'), ('Marketing', 'Marketing'), ('Business', 'Business'), ('Social Sciences', 'Social Sciences'), ('', 'Course category')], max_length=50),
        ),
    ]
