# Generated by Django 5.0.1 on 2024-01-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Health and Fitness', 'Health and Fitness'), ('Languages', 'Languages'), ('Engineering', 'Engineering'), ('Design', 'Design'), ('Personal Development', 'Personal Development'), ('Marketing', 'Marketing'), ('Business', 'Business'), ('Art and Creativity', 'Art and Creativity'), ('', 'Course category'), ('Social Sciences', 'Social Sciences')], max_length=50),
        ),
    ]
