# Generated by Django 5.0.1 on 2024-01-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Marketing', 'Marketing'), ('Design', 'Design'), ('', 'Course category'), ('Social Sciences', 'Social Sciences'), ('Science', 'Science'), ('Engineering', 'Engineering'), ('Health and Fitness', 'Health and Fitness'), ('Personal Development', 'Personal Development'), ('Art and Creativity', 'Art and Creativity'), ('Business', 'Business'), ('Languages', 'Languages')], max_length=50),
        ),
    ]
