# Generated by Django 5.0.1 on 2024-01-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Personal Development', 'Personal Development'), ('Languages', 'Languages'), ('Design', 'Design'), ('Engineering', 'Engineering'), ('', 'Course category'), ('Business', 'Business'), ('Science', 'Science'), ('Technology', 'Technology'), ('Social Sciences', 'Social Sciences'), ('Marketing', 'Marketing'), ('Art and Creativity', 'Art and Creativity'), ('Health and Fitness', 'Health and Fitness')], max_length=50),
        ),
    ]
