# Generated by Django 5.0.1 on 2024-01-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('Health and Fitness', 'Health and Fitness'), ('Science', 'Science'), ('Social Sciences', 'Social Sciences'), ('Art and Creativity', 'Art and Creativity'), ('Business', 'Business'), ('', 'Course category'), ('Technology', 'Technology'), ('Personal Development', 'Personal Development'), ('Design', 'Design'), ('Languages', 'Languages')], max_length=50),
        ),
    ]
