# Generated by Django 5.0.1 on 2024-01-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Personal Development', 'Personal Development'), ('Social Sciences', 'Social Sciences'), ('Design', 'Design'), ('Business', 'Business'), ('Art and Creativity', 'Art and Creativity'), ('Languages', 'Languages'), ('Technology', 'Technology'), ('Marketing', 'Marketing'), ('Health and Fitness', 'Health and Fitness'), ('Science', 'Science')], max_length=50),
        ),
    ]
