# Generated by Django 5.0.1 on 2024-01-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='overall_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Business', 'Business'), ('Personal Development', 'Personal Development'), ('Technology', 'Technology'), ('Art and Creativity', 'Art and Creativity'), ('Marketing', 'Marketing'), ('Health and Fitness', 'Health and Fitness'), ('Languages', 'Languages'), ('Social Sciences', 'Social Sciences'), ('Science', 'Science'), ('Design', 'Design')], max_length=50),
        ),
    ]
