# Generated by Django 5.0.1 on 2024-01-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Science', 'Science'), ('Marketing', 'Marketing'), ('Art and Creativity', 'Art and Creativity'), ('Engineering', 'Engineering'), ('Health and Fitness', 'Health and Fitness'), ('Design', 'Design'), ('Languages', 'Languages'), ('Business', 'Business'), ('Social Sciences', 'Social Sciences'), ('Technology', 'Technology'), ('Personal Development', 'Personal Development')], max_length=50),
        ),
    ]
