# Generated by Django 5.0.1 on 2024-01-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Languages', 'Languages'), ('Social Sciences', 'Social Sciences'), ('Design', 'Design'), ('Engineering', 'Engineering'), ('Art and Creativity', 'Art and Creativity'), ('Science', 'Science'), ('Business', 'Business'), ('Technology', 'Technology'), ('Health and Fitness', 'Health and Fitness'), ('Marketing', 'Marketing'), ('Personal Development', 'Personal Development')], max_length=50),
        ),
    ]
