# Generated by Django 5.0.1 on 2024-01-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Health and Fitness', 'Health and Fitness'), ('Personal Development', 'Personal Development'), ('Art and Creativity', 'Art and Creativity'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Engineering', 'Engineering'), ('Science', 'Science'), ('Business', 'Business'), ('Social Sciences', 'Social Sciences'), ('Languages', 'Languages')], max_length=50),
        ),
    ]
