# Generated by Django 5.0.1 on 2024-01-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Business', 'Business'), ('Social Sciences', 'Social Sciences'), ('Marketing', 'Marketing'), ('Design', 'Design'), ('Technology', 'Technology'), ('Engineering', 'Engineering'), ('Languages', 'Languages'), ('Health and Fitness', 'Health and Fitness'), ('', 'Choose category'), ('Art and Creativity', 'Art and Creativity'), ('Personal Development', 'Personal Development'), ('Science', 'Science')], max_length=50),
        ),
    ]
