# Generated by Django 5.0.1 on 2024-01-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Health and Fitness', 'Health and Fitness'), ('Marketing', 'Marketing'), ('Languages', 'Languages'), ('Science', 'Science'), ('Personal Development', 'Personal Development'), ('', 'Choose category'), ('Art and Creativity', 'Art and Creativity'), ('Social Sciences', 'Social Sciences'), ('Business', 'Business'), ('Design', 'Design'), ('Technology', 'Technology'), ('Engineering', 'Engineering')], max_length=50),
        ),
    ]
