# Generated by Django 5.0.1 on 2024-01-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Social Sciences', 'Social Sciences'), ('Art and Creativity', 'Art and Creativity'), ('Technology', 'Technology'), ('Engineering', 'Engineering'), ('Languages', 'Languages'), ('Business', 'Business'), ('Marketing', 'Marketing'), ('', 'Choose category'), ('Design', 'Design'), ('Science', 'Science'), ('Health and Fitness', 'Health and Fitness'), ('Personal Development', 'Personal Development')], max_length=50),
        ),
    ]
