# Generated by Django 5.0.1 on 2024-01-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Social Sciences', 'Social Sciences'), ('Engineering', 'Engineering'), ('Science', 'Science'), ('Languages', 'Languages'), ('Marketing', 'Marketing'), ('Design', 'Design'), ('Technology', 'Technology'), ('', 'Choose category'), ('Business', 'Business'), ('Health and Fitness', 'Health and Fitness'), ('Art and Creativity', 'Art and Creativity'), ('Personal Development', 'Personal Development')], max_length=50),
        ),
    ]
