# Generated by Django 5.0.1 on 2024-01-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Science', 'Science'), ('Social Sciences', 'Social Sciences'), ('Engineering', 'Engineering'), ('Health and Fitness', 'Health and Fitness'), ('Languages', 'Languages'), ('Design', 'Design'), ('Technology', 'Technology'), ('Art and Creativity', 'Art and Creativity'), ('', 'Choose category'), ('Marketing', 'Marketing'), ('Personal Development', 'Personal Development'), ('Business', 'Business')], max_length=50),
        ),
    ]
