# Generated by Django 5.0.1 on 2024-01-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Social Sciences', 'Social Sciences'), ('', 'Choose category'), ('Art and Creativity', 'Art and Creativity'), ('Technology', 'Technology'), ('Health and Fitness', 'Health and Fitness'), ('Languages', 'Languages'), ('Marketing', 'Marketing'), ('Personal Development', 'Personal Development'), ('Business', 'Business'), ('Design', 'Design'), ('Science', 'Science')], max_length=50),
        ),
    ]
