# Generated by Django 5.0.1 on 2024-01-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Health and Fitness', 'Health and Fitness'), ('Marketing', 'Marketing'), ('Social Sciences', 'Social Sciences'), ('Business', 'Business'), ('Languages', 'Languages'), ('Engineering', 'Engineering'), ('Science', 'Science'), ('', 'Choose category'), ('Art and Creativity', 'Art and Creativity'), ('Personal Development', 'Personal Development'), ('Technology', 'Technology'), ('Design', 'Design')], max_length=50),
        ),
    ]
