# Generated by Django 5.0.1 on 2024-01-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Health and Fitness', 'Health and Fitness'), ('', 'Choose category'), ('Technology', 'Technology'), ('Art and Creativity', 'Art and Creativity'), ('Personal Development', 'Personal Development'), ('Engineering', 'Engineering'), ('Languages', 'Languages'), ('Business', 'Business'), ('Science', 'Science'), ('Marketing', 'Marketing'), ('Social Sciences', 'Social Sciences'), ('Design', 'Design')], max_length=50),
        ),
    ]
