# Generated by Django 5.0.1 on 2024-01-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Science', 'Science'), ('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('', 'Choose category'), ('Social Sciences', 'Social Sciences'), ('Health and Fitness', 'Health and Fitness'), ('Art and Creativity', 'Art and Creativity'), ('Languages', 'Languages'), ('Personal Development', 'Personal Development'), ('Business', 'Business'), ('Technology', 'Technology'), ('Design', 'Design')], max_length=50),
        ),
    ]
