# Generated by Django 5.0.1 on 2024-01-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Science', 'Science'), ('Health and Fitness', 'Health and Fitness'), ('Technology', 'Technology'), ('Engineering', 'Engineering'), ('Design', 'Design'), ('', 'Choose category'), ('Social Sciences', 'Social Sciences'), ('Marketing', 'Marketing'), ('Art and Creativity', 'Art and Creativity'), ('Languages', 'Languages'), ('Business', 'Business'), ('Personal Development', 'Personal Development')], default='Technology', max_length=50),
        ),
    ]
