# Generated by Django 5.0.1 on 2024-01-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Languages', 'Languages'), ('Personal Development', 'Personal Development'), ('Technology', 'Technology'), ('Science', 'Science'), ('', 'Choose category'), ('Marketing', 'Marketing'), ('Health and Fitness', 'Health and Fitness'), ('Art and Creativity', 'Art and Creativity'), ('Engineering', 'Engineering'), ('Social Sciences', 'Social Sciences'), ('Design', 'Design'), ('Business', 'Business')], default='Technology', max_length=50),
        ),
    ]
