# Generated by Django 5.0.1 on 2024-01-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Science', 'Science'), ('', 'Choose category'), ('Health and Fitness', 'Health and Fitness'), ('Languages', 'Languages'), ('Art and Creativity', 'Art and Creativity'), ('Technology', 'Technology'), ('Personal Development', 'Personal Development'), ('Design', 'Design'), ('Social Sciences', 'Social Sciences'), ('Business', 'Business'), ('Engineering', 'Engineering')], default='Technology', max_length=50),
        ),
    ]
