# Generated by Django 5.0.1 on 2024-02-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_alter_course_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='categories',
            new_name='category',
        ),
    ]
