# Generated by Django 5.0.1 on 2024-03-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_alter_course_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
    ]
